- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  roles:
    - brew
    - git
    - {role: package_manager, tags: ['bootstrap']} 
    - {role: zsh, tags: ['bootstrap']} 
    - cscope
    - ctags
    - fzf
    - vim
    - tmux
    - {role: openconnect, when: ansible_os_family == "Debian"}
    - role: macos
      timezone: "{{ macos_timezone }}"
      computer_sleep_time: "{{ macos_computer_sleep_time }}"
      display_sleep_time: "{{ macos_display_sleep_time }}"
      os_defaults: "{{ macos_os_defaults }}"
      when: ansible_os_family == "Darwin"
    - java
    #- external_drive
