---
- name: check flags for the user library folder
  changed_when: false
  command: ls -lOd ~/Library
  register: library_flags

- name: unhide the user library folder
  command: chflags nohidden ~/Library
  when: "'hidden' in library_flags"

- name: create the development folder
  file:
      path: "{{ development_dir }}"
      state: directory

- name: create the screenshots folder
  file: path=~/Pictures/Screenshots state=directory

- name: Set system defaults
  script: set-defaults.sh
  changed_when: false

- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: no

- name: Ensure custom Terminal profile is added.
  shell: "open roles/macos/files/IW.terminal"
  #  changed_when: false
  #  when: "'Solarized-Dark' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string IW
    - defaults write com.apple.terminal 'Startup Window Settings' -string IW
  #changed_when: false
  #when: "'Solarized-Dark' not in terminal_theme.stdout"

  # SET CONFIGURATIONS
  # Credit to Nick Charlton
  # https://nickcharlton.net/posts/automating-macos-using-ansible.html
- name: Remove all items from the Dock
  shell: /usr/local/bin/dockutil --remove all

- name: Set the default Dock items
  shell: "/usr/local/bin/dockutil --add {{ item }} --no-restart"
  with_items:
    - /Applications/Safari.app
    - "\"/Applications/System Preferences.app\""
    - /Applications/Utilities/Terminal.app
    - /Applications/Utilities/Console.app
    - "/Applications --section others"
    - "~/Downloads --section others"

- name: Reduce the size of the Dock to 30 points
  shell: defaults write com.apple.dock tilesize -int 30

  #- name: Disable the Screensaver
  #  shell: defaults write com.apple.screensaver idleTime 0

- name: Arrange Files by Kind
  shell: |
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy kind" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy kind" ~/Library/Preferences/com.apple.finder.plist

- name: Set the Grid Spacing for Files
  shell: |
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 54" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 30" ~/Library/Preferences/com.apple.finder.plist

- name: Use Smaller Icons
  shell: |
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 48" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist

- name: Show ~/Library
  shell: chflags nohidden ~/Library

- name: Show Drives on the Desktop
  shell: defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

- name: Show External Drives on the Desktop
  shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

- name: Show Removable Media on the Desktop
  shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

- name: Show Hidden Files
  shell: defaults write com.apple.finder AppleShowAllFiles -bool true

- name: Show File Extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Show the Status Bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: Show the Path Bar in Finder
  shell: defaults write com.apple.finder ShowPathbar -bool true

- name: Restart Finder
  shell: killall Finder

  #- name: Check for Terminal.app PLIST symlink
  #  stat: path=~/Library/Preferences/com.apple.Terminal.plist
  #  register: terminal_app_plist
  #
  #- name: Backup current Terminal.app PLIST
  #  copy:
  #      src: ~/Library/Preferences/com.apple.Terminal.plist
  #      dest: ~/Library/Preferences/com.apple.Terminal.plist.BAK
  #      #when: terminal_app_plist.stat.islnk is not defined
  #
  #- name: Delete the current Terminal.app PLIST
  #  file: path=~/Library/Preferences/com.apple.Terminal.plist state=absent
  #  #when: terminal_app_plist.stat.islnk is not defined
  #
  #- name: Symlink this project's Terminal.app PLIST
  #  file: path=~/Library/Preferences/com.apple.Terminal.plist
  #        src=macos/files/com.apple.Terminal.plist
  #        state=link
  #        force=yes
  #        follow=False
  #        #when: terminal_app_plist.stat.islnk is not defined

- name: Configure macOS Operating System defaults
  plist:
    dest: "{{ item.domain }}"
    # Note that we must access values using the square brackets or Ansible
    # casts all values to strings
    values: "{{ item['values'] }}"
    container: "{{ item.container | default(None) }}"
  become: "{{ item.become | default(false) }}"
  with_items: "{{ os_defaults }}"
  tags:
    - terminal
